### ISSUE TITLE
Time and Weather Synced with Real Life Places

### ISSUE THREAD

**Issue by S4pphire-hue** [qbcore-framework/qb-weathersync#15]
What the title says.
You could make it synced with a timezone and simply change it from the config whether you want both of the things synced or only one of them

**Comment by Trusukas** [comment]
Yeah it's a good idea but don't make it as a default 'cause it's not recommended for people that has depressions or something like that, are always with bad moods and you are coming from cold moods of outside into room to play and make some fun in-game and then you see night, everywhere dark, cold etc. Or it's night outside and In-game is night that's so sad moods.

**Comment by S4pphire-hue** [comment]
I forgot to add that, maybe server owners don't want real time sync so they can choose to just remove that in the config

**Comment by Synthethics** [comment]
First of all - Not an issue, fits more of an Enhancement or Suggestion label.
I believe resources in the past have used this in combination with some kind of API from Weather Websites. However, some of these were very limited to a few pulls per day, which, with quick changing weather isn't much of an update. However, I'd like to see this as an optional configuration.

**Comment by ARSSANTO** [comment]
same for me too its a good feature to have real time but some of my point of view if there is a config for switch real time or game time that will be more better i tested the current one its like OP the shadow moving are too smooth

**Comment by zfbx** [comment]
time syncing wouldn't be too bad to do as an option, weather would require an API key and most weather APIs have very strict limits. I personally don't see the appeal to this as if you play every night, it's night for you all the time.. and if you want it to be day you have to physically be on during the day. also there's a lot of GTA systems that depend on time for events and such like ped density, beach population, lights and such. Personally seems a bit extreme to me.
