### ISSUE TITLE
Issue with day en nicht

### ISSUE THREAD

**Issue by MaDHouSe79** [qbcore-framework/qb-weathersync#30]
I already place a topic but on the wrong place... so here again :)

I wonder why it's always nighttime on my server, I have to change the time every time, to get it daytime, no matter how I set it, if I turn off all timers and timesinc off then it's still always at night, really this is so annoying.

**Comment by zfbx** [comment]
can you give some more information on your configuration? how up to date are your resources, what OS are you running? do you have any visual mods like NVE?

**Comment by MaDHouSe79** [comment]
Hi, zfbx, thnx you for your reply,

but i don't really understand what a completely different mod(graphics on my own computer) should have influence on the server day and night cycle? and even when i just start it, it's always nighttime, i can just change it from night to day in game, but it's a lot more often night than day, I have to set the server to day every time because the nights are sooooo very long and I don't have any mods that affect time or weather on the server. I downloaded everything from qb github itself and put it together, but this should not have the influence that it is always only night on the server right?. i even try to change the timers but stil nothing, ow and clear cache, even with other people it is always only night... I have not changed in any settings or anything, and when I turn my ESX server back on I have no problems at all. but i realy want to use qb.  so im a little stuck now, cause normal i find the issue but now, i redownload it en put a new one in it, but stil nicht :D so i don't understand why this happened, and its not only on my computer but also other players.

**Comment by MaDHouSe79** [comment]
well.. that what not the issue, did not fix it,

**Comment by zfbx** [comment]
maps can effect the daylight cycle for sure like interiors usually set the time to night when you're inside them to prevent the sun casting through the walls, it's possible one of them could be bleeding into global space from being configured improperly. 

NVE has server mods and also I wasn't sure if you meant it was your client that has the issue and some light mods have settings to make it constantly show as one time or another for glamour shots

does anything happen if you run `/noon`

**Comment by MonkeyWhisper** [comment]
Do you have by any chance vMenu on your server? 

> well.. that what not the issue, did not fix it,

**Comment by MaDHouSe79** [comment]
yes i have vMenu but i disable all time and weather, we can't use time and weather in vMenu, everting is false, so this can't be the issue because before i never had a issue with this. same that my server alwayss start in nicht and never with daylight. i have to change this by hand evertime. over and over again.

**Comment by MonkeyWhisper** [comment]
> yes i have vMenu but i disable all time and weather, we can't use time and weather in vMenu, everting is false, so this can't be the issue because before i never had a issue with this. same that my server alwayss start in nicht and never with daylight. i have to change this by hand evertime. over and over again.

Okay, have you tried removing vMenu, temporarily just for testing purposes and restart the city. See if it happens?

**Comment by MaDHouSe79** [comment]
yes i even disable evering i had extra installed like all milos and car packs, so everting, but qb running and stil its night, i had today 1 time, it was day time but overall it is alway night. i even changes some values in code of qb-weathersync to force to start in day time but even that does not work.

**Comment by MonkeyWhisper** [comment]
> yes i even disable evering i had extra installed like all milos and car packs, so everting, but qb running and stil its night, i had today 1 time, it was day time but overall it is alway night. i even changes some values in code of qb-weathersync to force to start in day time but even that does not work.

And if you do stop the resource weathersync, meaning it does not load at all and you restart the server, does it come at night?

**Comment by MonkeyWhisper** [comment]
Can you tag me in QBCore Discord? My tag is MonkeyWhisper#0001, I want to debug this issue with you.

**Comment by MaDHouSe79** [comment]
Well i just install a compleet new server with the translation in it, and without the weathersync, and it starts in daytime, but when i complety restart the server and now with weathersync loaded, the server starts in night again.  so now i have noting but only qb-core and its needs like connectqueue and oxmysql progressbar screenshot-basic, and if i dont load weathersync it start in daytime, but if i turn on weathersync  and restart the server and beforce restart i always clear the cache, and its night again :)

**Comment by MonkeyWhisper** [comment]
> Well i just install a compleet new server with the translation in it, and without the weathersync, and it starts in daytime, but when i complety restart the server and now with weathersync loaded, the server starts in night again. so now i have noting but only qb-core and its needs like connectqueue and oxmysql progressbar screenshot-basic, and if i dont load weathersync it start in daytime, but if i turn on weathersync and restart the server and beforce restart i always clear the cache, and its night again :)

That sounds bizarre. I just installed a fresh copy, right off txadmin and I'm not having this issue. I was just working on it.

What is your Discord?

**Comment by MaDHouSe79** [comment]
My discord is name MaDHouSe#0011
