### ISSUE TITLE
Freezetime not working

### ISSUE THREAD

**Issue by SmithyPD** [qbcore-framework/qb-weathersync#44]
Freezetime no longer working, when you unfreeze time it returns to the time you froze it at, 
eg. you set time for noon, freezetime, time still progresses.. its getting dark. unfreeze time and it goes back to noon.

**Comment by MatthewRorke** [comment]
I have this issue.

**Comment by TotoYmola** [comment]
same it will freeze the time..but not the night and day

**Comment by MatthewRorke** [comment]
Pull request fixes this issue.
