### ISSUE TITLE
Set length of day based upon IRL time

### ISSUE THREAD

**Issue by erikmeyer08** [qbcore-framework/qb-weathersync#53]
Can an enhancement be added to allow the adjustment of time based upon IRL time?

EX: 1 game day = 1 hour IRL

**Comment by nullvariable** [comment]
you can use the Config settings to accomplish this:
If I recall correctly,  `Config.BaseTime = 0`  will sync the time with the server time, 1 minute should be 1 minute. Default is 1 minute = 8 minutes

**Comment by w4fflz** [comment]
Is this still an issue needing researched?

**Comment by w4fflz** [comment]
Closing issue due to no response.
