### ISSUE TITLE
blackout does not work.

### ISSUE THREAD

**Issue by MaDHouSe79** [qbcore-framework/qb-weathersync#61]
blackout does not work, noting happem. no errors

**Comment by w4fflz** [comment]
Just tested it on my localhost and it worked as intended.  Are you using any other weather scripts?

**Comment by MaDHouSe79** [comment]
is it pissoble that this came from a other qb-admin? cause i see some time some flikkering from the lights, and thats realy it, i change the `Wait(100)` to `Wait(1)` to prefent the light flikkering, but it does not work, so i cant do the big bank heist cause the blackout does not work for some reason :)

**Comment by MaDHouSe79** [comment]
I foudnd the issue, someone add SetBlackout(false) in his script, thats why it does not work, bit i fix it, thnx :)

**Comment by jatinbansaljb** [comment]
how to fix can you tell me same issue when i did blackout still light not getting off
