### ISSUE TITLE
[BUG] blackout not working

### ISSUE THREAD

**Issue by alfiswielki** [qbcore-framework/qb-weathersync#62]
https://streamable.com/1tposm
The lights don't go out, they just flash.... I only use qb-weathersync. No console errors....

**Comment by jatinbansaljb** [comment]
same issue any got solution ?

**Comment by FrequencyRoleplay** [comment]
Firstperson aiming was the culprit for me. 

check for any script that has blackout(false)

**Comment by MarioFincMan** [comment]
> 

This is the solution!
