### ISSUE TITLE
[SUGGESTION] Real Time

### ISSUE THREAD

**Issue by mataskc** [qbcore-framework/qb-weathersync#63]
**Describe the feature you'd like**
I think it would be cool if you could synchronize the time in game with the time on the game server

**Comment by CptNoHand** [comment]
I agree. A option for that would be amazing.

**Comment by NeonLifeRPde** [comment]
Bump its very good Idea!

**Comment by 6utzeit** [comment]
That would be so nice.

**Comment by Tweafky** [comment]
Also think it's a good idea, everything can be optional.

**Comment by alexvermaning0** [comment]
i want to upgrade this Suggestion by allowing to use real life weather sync. using openwheathermap

**Comment by JensGryspeert** [comment]
I'm starting to work on this. I'll set here a PR in approx a week and we'll see if it will be accepted.

**Comment by mataskc** [comment]
Nice! Good luck.

**Comment by mataskc** [comment]
> I'm starting to work on this. I'll set here a PR in approx a week and we'll see if it will be accepted.

Nice! Good luck.

**Comment by JensGryspeert** [comment]
Update: This evening I'll create the correct commits and be sure it will match the codestyle as the guidelines insist. If someone is available to test this on his server to see if this has no issues please be my guest. On mine server it worked perfectly and the time was synchronized with the real life time.

**Comment by JensGryspeert** [comment]
PR is available: https://github.com/qbcore-framework/qb-weathersync/pull/74
