### ISSUE TITLE
[BUG] AUTOMATIC WEATHER CHANGE

### ISSUE THREAD

**Issue by alfiswielki** [qbcore-framework/qb-weathersync#65]
I DON'T KNOW IF IT'S A BUG OR IF I'VE GOT SOMETHING WRONG, BUT APART FROM NIGHT AND DAY YOU DON'T GET RAIN OR STORMS.... HERE IS A PICTURE OF WHETHER I HAVE GOT EVERYTHING RIGHT, WHAT DO YOU THINK?
![WEATHER](https://user-images.githubusercontent.com/111529419/192314324-ead90566-f846-4adf-8492-d390e868a6da.png)

**Comment by NeonLifeRPde** [comment]
Same at our server idk why this keeps happening!

**Comment by KrnkTV** [comment]
did someone fix this?
